### ISSUE TITLE
agent_ctl.sh: nameserver resolution fails for servers at 127.0.0.1[0-9]+

### ISSUE THREAD

**Issue by ericpromislow** [cloudfoundry-incubator/consul-release#14]
We couldn't get consul_agent starting on cf-release v231 because the nameserver was at 127.0.0.11, but the nameservers variable in agent_ctl.sh didn't include it.

**Comment by Amit-PivotalLabs** [comment]
Closing this issue in favour of the PR you submitted.

**Comment by Amit-PivotalLabs** [comment]
For reference: https://github.com/cloudfoundry-incubator/consul-release/pull/15
