### ISSUE TITLE
Why does consul-agent not allow to set DNS caching?

### ISSUE THREAD

**Issue by AbelHu** [cloudfoundry-incubator/consul-release#26]
From [DNS caching](https://www.consul.io/docs/guides/dns-cache.html), we know that consul allows to configure dns_config.allow_stale and dns_config.max_stale for performance and scalability. But in the [configure](https://github.com/cloudfoundry-incubator/consul-release/blob/8f3e898bcf6bd798334b3db2eefe179564dc8392/src/confab/config/consul_config_definer.go#L13-L36) of consul-agent, we found no settings for DNS caching. 
What is the reason for that?

**Comment by Amit-PivotalLabs** [comment]
Hi @AbelHu 

Sorry for the delayed response.

There's no particular reason for these properties to not be exposed, except perhaps for keeping the interface for this release slim and only exposing crucially important properties.  Exposing the properties you mentioned is not a priority at this time, but we'd welcome a pull request.  If you're interested in submitting a PR for this feature, be sure to check out the [contributing instructions](https://github.com/cloudfoundry-incubator/consul-release#contributing).

If you were to do this, I would expose this via job spec properties on the `consul_agent` job called `consul.dns_config.max_stale` and `consul.dns_config.max_stale`.

**Comment by AbelHu** [comment]
@Amit-PivotalLabs Thanks for your response. We will consider to submit a PR later.

**Comment by keymon** [comment]
@AbelHu Hi, are you considering do a PR for this?

**Comment by Amit-PivotalLabs** [comment]
@keymon @AbelHu FYI: https://www.pivotaltracker.com/story/show/126916281
