### ISSUE TITLE
Consul agent fails to start when confab's node.external_ip is null

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry-incubator/consul-release#28]
Running in a deployment with dynamic networks, the rendered confab.json looks like this:

```json
{
   "consul" : {  },
   "node" : {
      "name" : "kube-node",
      "external_ip" : null,
      "index" : 0
   }
}
```

When the `external_ip` is null, the `bind_addr` option in the generated consul configuration is set to the empty string. This forces consul to attempt to calculate the `advertise` address by looking at the network adapters with addresses in the private IP space.

If multiple adapters exist with private IPs, consul fails with the following:

```
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
```

The multiple adapter scenario was encountered while doing a rolling deployment of a bosh job that contained bridge interfaces for overlay networks and containers.

When the `spec.address` from bosh is null, it seems like the `bind` or `advertise` address should be calculated by connecting to the consul server and using the local address of the connection. This would avoid the problem while still using `spec.address` when bosh has that information.

**Comment by Amit-PivotalLabs** [comment]
@sykesm 

There's some discussion in https://github.com/cloudfoundry-incubator/consul-release/issues/32 about a possibly upcoming `spec.ip` method provided by BOSH.  Would that solve your problem?

/cc @cppforlife

**Comment by sykesm** [comment]
@Amit-PivotalLabs It depends on how it's done and how it works. If there's only one dynamic network, it will probably be fine. If there are multiple dynamic networks and you chose the one associated with the default gateway, it might.

At the end of the day, something needs to choose the network(s) and the addresses. This is why we suggested you dial the consul server to find the local address.

**Comment by Amit-PivotalLabs** [comment]
I'd prefer to know the exact requirements in addition to the proposed solution.  Given what I think your requirements are, having a BOSH-provided helper would be preferable.  It sounds like the problem you're describing might impact things other than Consul, and might make more sense at the BOSH level.  Have you discussed this with the BOSH team at all?  Are they aware of your exact requirements?

**Comment by sykesm** [comment]
With bosh "v1", my understanding is that you have access to all of the networks via [`spec.networks`][1] so once the IP is available, you'll still have the problem of choosing whether you listen on all networks or deciding which one.

For bosh "v2", links can be [associated with a network][2] so, if links are used, you should be covered.

[1]: https://bosh.io/docs/jobs.html#properties
[2]: https://bosh.io/docs/links.html#custom-network

**Comment by Amit-PivotalLabs** [comment]
Closing in favour of #32

**Comment by cppforlife** [comment]
@sykesm I m planning to add `network: blah` on the job similar to links for the operator to specify which ip to expose to the job templates and continue defaulting to default: gateway picked network.
