### ISSUE TITLE
Do not require unused certs when running consul_agent in client/server mode

### ISSUE THREAD

**Issue by flawedmatrix** [cloudfoundry-incubator/consul-release#30]
When specifying BOSH job level properties for the `consul_agent` job, it currently requires all the following properties: ["consul.agent_cert", "consul.agent_key", "consul.server_cert", "consul.server_key"].

Looking at the confab source code, it appears that when running in server mode, it doesn't actually need "consul.agent_cert" and "consul.agent_key", and vice versa for client mode.

I confirmed this by setting the unnecessary keys to empty string and consul continued to worked successfully.

Maybe there could be some BOSH template level branching logic to conditionally require the necessary keys.

**Comment by christianang** [comment]
Hi @flawedmatrix,

This has been added to the latest release in commit 59042326a59a38fda521af5a8a5c6cbe13620acd.

Thanks,
Christian and @kkallday
