### ISSUE TITLE
DNS modifications are lost on system reboot with stemcell 3262.2 and consul-release 97

### ISSUE THREAD

**Issue by sykesm** [cloudfoundry-incubator/consul-release#31]
The consul agent's pre-start script appends `127.0.0.1` to `/etc/resolvconf/resolv.conf.d/head` and the bosh agent in stemcell 3262.2 writes the dns server entries to the same file.

When a system running the consul agent is rebooted, the pre-start script does not run but the agent initialization scripts do so the modifications made to /etc/resolvconf/resolv.conf.d/head are lost and `127.0.0.1` is no longer in `/etc/resolv.conf`.

The net result is that any job that relies on the consul for DNS resolution fails after a reboot.

**Comment by cppforlife** [comment]
@sykesm im assuming you are on softlayer. we have recently fixed that problem in the agent: https://github.com/cloudfoundry/bosh-agent/commit/b74fb972dc671bcabc4cabe2f04d2e08af74a08c. i dont believe it's made into any stemcell version yet.

**Comment by sykesm** [comment]
@cppforlife yes, on SoftLayer. We did see the pending change to the agent but, as you said, it's not in any available stemcell.

That will help correct this particular problem but we hit several others related to pre-start when SoftLayer rolled VMs in a pod to apply security fixes. One example is in cloudfoundry/capi-release#25.

**Comment by Amit-PivotalLabs** [comment]
@sykesm can I close out this issue, as you expect a fix in the upcoming stemcell?

**Comment by sykesm** [comment]
Sure.
