### ISSUE TITLE
Consul fails to start when dynamic networking on SoftLayer

### ISSUE THREAD

**Issue by andrew-edgar** [cloudfoundry-incubator/consul-release#32]
With the change introduced with CF 238 and the commit specified here ...
https://github.com/cloudfoundry-incubator/consul-release/commit/55cb4a414c687d0ec91a5ac9d2358aec5fe7d930#diff-25ba660257040d54208c35f5397fb084

The external_ip is filled in as a FQDN instead of an IP address. When deployed on SoftLayer with dynamic networking.

The memberlist.go calls net.ParseIP which expects an IP address.

The bosh team said they are looking at adding spec.ip for cases where an IP address is required.  But that spec.address does NOT guarantee an IP address.

**Comment by Amit-PivotalLabs** [comment]
Thank @andrew-edgar.  When you say that the BOSH team is looking into `spec.ip`, do you know what the ETA for that is?

We switched from our custom IP discovery function to the BOSH-provided `spec.address` under the expectation that it would do the same thing, but seems like it's actually not suitable for all networks.  I thought I remember @cppforlife saying that in the case of dynamic networks, BOSH would stall plan to provide a correct value for `spec.address` by rendering the template after the VM had been provisioned.

/cc @cppforlife @sykesm
