### ISSUE TITLE
Failed to start consul agent when using multiple network interfaces

### ISSUE THREAD

**Issue by kei-yamazaki** [cloudfoundry-incubator/consul-release#37]
I'm using cf-release v238.
And bind multiple network interfaces to vm, can not start consul agent.

Following is consul's logs.

```
root@6ec2557d-c9aa-4407-948d-322aced46655:/var/vcap/bosh_ssh/bosh_s844df1fz# less /var/vcap/sys/log/consul_agent/consul_agent.stdout.log
==> Starting Consul agent...
==> Error starting agent: Failed to get advertise address: Multiple private IPs found. Please configure one.
{"timestamp":"1471411596.191884995","source":"confab","message":"confab.agent-client.verify-joined.members.request","log_level":1,"data":{"wan":false}}
{"timestamp":"1471411596.192110062","source":"confab","message":"confab.agent-client.verify-joined.members.request.failed","log_level":2,"data":{"error":"Get http://127.0.0.1:8500/v1/agent/members: dial tcp 127.0.0.1:8500: getsockopt: connection refused","wan":false}}
```

I think that `bind_addr` option should be specified in consul's configuration file.

**Comment by Amit-PivotalLabs** [comment]
You may wish to use v240, here's the relevant note from the [release notes](https://github.com/cloudfoundry/cf-release/releases/tag/v240#internal-components):

> #### `consul-release` (includes `consul_agent` job)
>
> * Bumped from v92 to [v101](https://github.com/cloudfoundry-incubator/consul-release/releases/tag/v101). Functional changes:
>   * Fix `consul_agent` job when running on BOSH VMs with multiple dynamic networks. [details](https://www.pivotaltracker.com/story/show/126793339)

**Comment by kei-yamazaki** [comment]
@Amit-PivotalLabs, thank you for a replying.
I'll try to use v240.
