### ISSUE TITLE
Consul get failing state on CloudFoundry fresh install - consul not running after update

### ISSUE THREAD

**Issue by nunodio** [cloudfoundry-incubator/consul-release#38]
When I deploy CloudFoundry using BOSH I got the _consul vm_ with _failing state_ .

```shell
  Started updating job consul_z1 > consul_z1/0 (76de227d-fa11-46e6-a0ad-0c58bc9b935a) (canary). Failed: 'consul_z1/0 (76de227d-fa11-46e6-a0ad-0c58bc9b935a)' is not running after update. Review logs for failed jobs: consul_agent (00:11:50)

Error 400007: 'consul_z1/0 (76de227d-fa11-46e6-a0ad-0c58bc9b935a)' is not running after update. Review logs for failed jobs: consul_agent
```

```shell
[ cf-release]$ bosh vms
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+
| VM                                                                        | State   | AZ  | VM Type   | IPs           |
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+
| api_worker_z1/0 (36e11a2d-7254-4ad8-887b-d416a2e62475)                    | running | n/a | small_z1  | 10.0.0.85     |
| api_z1/0 (90b154c0-0bfe-4c3f-b6bd-e1364a317c59)                           | running | n/a | large_z1  | 10.0.0.84     |
| blobstore_z1/0 (e1d5b7c6-4975-4dcf-9ab3-1c4e994e3c6a)                     | running | n/a | medium_z1 | 10.0.0.82     |
| consul_z1/0 (76de227d-fa11-46e6-a0ad-0c58bc9b935a)                        | failing | n/a | small_z1  | 10.0.0.33     |
| doppler_z1/0 (f83b07c7-49a1-435f-8de4-787109432944)                       | running | n/a | medium_z1 | 10.0.0.88     |
| etcd_z1/0 (8bbad503-c4cd-4e4c-84dc-9566fdb6b480)                          | running | n/a | medium_z1 | 10.0.0.29     |
| ha_proxy_z1/0 (7b4f37b2-8fd2-4371-adf1-95be56e3babb)                      | running | n/a | router_z1 | 10.0.0.21     |
|                                                                           |         |     |           | 192.168.0.104 |
| hm9000_z1/0 (f705d676-5b2c-4e0c-ae97-5419f751e5d9)                        | running | n/a | medium_z1 | 10.0.0.86     |
| loggregator_trafficcontroller_z1/0 (b73f2e28-a427-406a-a097-f08465e69271) | running | n/a | small_z1  | 10.0.0.89     |
| nats_z1/0 (8419e832-39dc-4363-8ffb-9e834e7ddf0c)                          | running | n/a | medium_z1 | 10.0.0.23     |
| postgres_z1/0 (d32aa3f8-28e2-4eb7-8e51-be85f9a1153b)                      | running | n/a | medium_z1 | 10.0.0.25     |
| router_z1/0 (b1d8aad7-e8a1-4d4c-bd48-37158deb51f5)                        | running | n/a | router_z1 | 10.0.0.26     |
| runner_z1/0 (44e2e50a-0a69-4a2f-9b4a-a973c43a9f26)                        | running | n/a | runner_z1 | 10.0.0.87     |
| stats_z1/0 (6e684cf4-f1d2-43c7-a561-6abc3f68ee45)                         | running | n/a | small_z1  | 10.0.0.81     |
| uaa_z1/0 (c3fb79e5-88cb-4331-a2a1-e30a2c3ca936)                           | running | n/a | medium_z1 | 10.0.0.83     |
+---------------------------------------------------------------------------+---------+-----+-----------+---------------+
```

Then I try to understand what happens and did an ssh into the consul vm.

```shell
root@0c5f6cf3-699a-4963-af6c-37fcb266522e:~# monit summary
The Monit daemon 5.2.5 uptime: 36m 

Process 'consul_agent'              not monitored
Process 'metron_agent'              running
System 'system_localhost'           running
```

Log File: `consul_agent.stderr.log`

```shell
error during start: timeout exceeded
error during start: timeout exceeded
```

Log File: `consul_agent.stdout.log`

```shell
==> WARNING: LAN keyring exists but -encrypt given, using keyring
==> WARNING: WAN keyring exists but -encrypt given, using keyring
==> WARNING: BootstrapExpect Mode is specified as 1; this is the same as Bootstrap mode.
==> WARNING: Bootstrap mode enabled! Do not enable unless necessary
==> Starting Consul agent...
==> Error starting agent: Failed to start Consul server: Failed to load cert/key pair: crypto/tls: failed to find any PEM data in certificate input
{"timestamp":"1471595855.086611509","source":"confab","message":"confab.agent-client.verify-joined.members.request","log_level":1,"data":{"wan":false}}
{"timestamp":"1471595855.086913347","source":"confab","message":"confab.agent-client.verify-joined.members.request.failed","log_level":2,"data":{"error":"Get http://127.0.0.1:8500/v1/agent/members: dial tcp 127.0.0.1:8500: getsockopt: connection refused","wan":false}}
```

_The last line repeats many times._

Here's my `cf-deployment.yml` file:
https://gist.github.com/nunodio/c160af872ed6d25294d692ee4efa53ea

I already tested this with Ubuntu and CentOS Stemcells for Openstack (different versions) with no success. 

Thanks in advance,
Nuno

**Comment by zankich** [comment]
@nunodio it appears as though your `agent_cert` is not a valid certificate https://gist.github.com/nunodio/c160af872ed6d25294d692ee4efa53ea#file-cf-deployment-yml-L1249-L1274. How did you generate the certificates? You can generate new certs by running https://github.com/cloudfoundry-incubator/consul-release/blob/master/scripts/generate-certs and then copying those certs into your deployment manifest.

**Comment by nunodio** [comment]
I had generated the certificates with the tool you mention. I identified the problem and it's related with the first and last line, which only uses 4 dashes "**-**" instead of 5 .

I copy the template from here:
``https://docs.cloudfoundry.org/deploying/common/consul-security.html``
 
In `agent_cert` and  `server_cert` attributes appears only 4 dashes. So the problem occurred when i copied the template from CF documentation.
Thank you for your help.

**Comment by Amit-PivotalLabs** [comment]
Thanks, I've opened a PR to update the docs: https://github.com/cloudfoundry/docs-deploying-cf/pull/124

**Comment by parthasarathi204** [comment]
Same issue . I am also started getting this issue all on a sudden today . I did not face this issue earlier . Is there any change in consul ?  Got the following error.
 Started updating instance consul_z1 > consul_z1/ed03cb12-8e4a-4a4b-898f-c577a1c99b0d (0) (canary). Failed: 'consul_z1/0 (ed03cb12-8e4a-4a4b-898f-c577a1c99b0d)' is not running after update. Review logs for failed jobs: consul_agent (00:03:12)

Error 400007: 'consul_z1/0 (ed03cb12-8e4a-4a4b-898f-c577a1c99b0d)' is not running after update. Review logs for failed jobs: consul_agent

Task 3 error

**Comment by paltanmoy** [comment]
I am also facing the same issue -
Started updating instance consul_z1 > consul_z1/c8e5d9ed-ec5c-4f0c-a353-1cf2bdc8fd85 (0) (canary). Failed: 'consul_z1/0 (c8e5d9ed-ec5c-4f0c-a353-1cf2bdc8fd85)' is not running after update. Review logs for failed jobs: consul_agent (00:03:09)

Error 400007: 'consul_z1/0 (c8e5d9ed-ec5c-4f0c-a353-1cf2bdc8fd85)' is not running after update. Review logs for failed jobs: consul_agent

consul_agent.stderr.log filled with -
error during start: timeout exceeded: "Unexpected response code: 500 (rpc error: failed to get conn: x509: certificate has expired or is not yet valid)"

In consul_agent.stdout.log- 
{"timestamp":"1502200891.857542753","source":"confab","message":"confab.agent-client.set-keys.list-keys.request.failed","log_level":2,"data":{"error":"Unexpected response code: 500 (rpc error: failed to get conn: x509: certificate has expired or is not yet valid)"}}

I am using cf-release version 270.  

`bosh status` 

 Name       Bosh Lite Director
  URL        https://127.0.0.1:25555
  Version    260.0.0 (00000000)
  User       admin
  UUID       63ddb6a6-d6fe-40e1-b16b-2ff6b2034c79
  CPI        warden_cpi
  dns        disabled
  compiled_package_cache enabled (provider: local)
  snapshots  disabled

**Comment by paltanmoy** [comment]
It worked after generating new certificates (using https://github.com/cloudfoundry/cf-release/blob/master/scripts/generate-consul-certs) and manually modifying the certificates (with the newly generated) in the manifest file (cf.yml).

**Comment by parthasarathi204** [comment]
Thanks. that worked
