### ISSUE TITLE
Consul agents won't start if the `consul.agent.servers.lan` property is not an IP but a DNS

### ISSUE THREAD

**Issue by keymon** [cloudfoundry-incubator/consul-release#4]
On GCE there is [no support for static ips](https://github.com/frodenas/bosh-google-cpi/issues/1), so one must use something powerDNS bosh job aliases (` 0.consul-z1.cf1.cloudfoundry.microbosh`) for service discovery to populate [variables like consul.agent.servers.lan](https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/spec#L23).

Consul is fine with this in general, but the scripts [`agent_ctl` on cf-release](https://github.com/cloudfoundry/cf-release/blob/v218/jobs/consul_agent/templates/agent_ctl.sh.erb#L125) or [in the new consul-release](https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/templates/agent_ctl.sh.erb#L142) expects that the property is an IP to be able to grep for the servers in the output of `consul members -status=alive`:

```
# /var/vcap/packages/consul/bin/consul members -status=alive
Node         Address         Status  Type    Build  Protocol  DC
consul-z1-0  10.0.0.5:8301   alive   server  0.5.2  2         dc1
router-z1-0  10.0.0.17:8301  alive   client  0.5.2  2         dc1
uaa-z1-0     10.0.0.22:8301  alive   client  0.5.2  2         dc1
api-z1-0     10.0.0.15:8301  alive   client  0.5.2  2         dc1
```

To solve this we can, for instance:

 1. try to resolve the DNS entries in the script: `consul_server_ip=$(host consul_server_hostname | tail -n 1 | cut -f 4 -d ' ')`
 2. grep for the jobname `consul members -status=alive | grep  consul-z1-0`
 3. grep for the string `alive server`, instead of the IPs

I guess the safest and simplest option is the last one.

**Comment by keymon** [comment]
I would do a PR on this, but I don't know which approach you prefer.

**Comment by Amit-PivotalLabs** [comment]
I will close this issue so we can consolidate the discussion in your PR: cloudfoundry-incubator/consul-release#5
