### ISSUE TITLE
Consider non server consul_agent issues when running out of disk space

### ISSUE THREAD

**Issue by youngm** [cloudfoundry-incubator/consul-release#46]
I recently had an issue where my / partition filled up with disk space.  If fixed the issue and later restarted the vm and the consul agent failed to start up.  I believe because one of its database files was not fully written do to running out of disk space.

To fix it i had to delete the contents of /var/vcap/store/consul_agent.

I wonder does a non server need to retain it's database?  Should non servers simply delete this directory every time it starts?

Or perhaps non server consul_agents should consider putting their database in /var/vcap/data which is usually bigger and less prone to running out of space?

Thoughts?

**Comment by Amit-PivotalLabs** [comment]
@youngm I believe this was fixed in https://github.com/cloudfoundry-incubator/consul-release/releases/tag/v108

**Comment by youngm** [comment]
Wow, that's amazing!  Fixes exactly this problem.  Sorry for being lazy.  Thanks @Amit-PivotalLabs !
