### ISSUE TITLE
Bug: Please fix the drain script so it handles a missing log folder gracefully

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry-incubator/consul-release#48]
*The drain script is not idempotent, but needs to be in case bosh tries to monit stop on a fresh VM*

It is possible with bosh to end up with a failed deployment that is impossible to update due to a bug in the consul release.  

The [drain script](https://github.com/cloudfoundry-incubator/consul-release/blob/master/jobs/consul_agent/templates/drain#L8-L9) assumes that the `/var/vcap/sys/log/consul_agent/` folder exists, but in some cases where the drain script will be used it does not and so bosh aborts when the drain script fails.

**Comment by Amit-PivotalLabs** [comment]
Thanks.  We'll look into this.  If this is indeed an issue, we will mark the release from the one that introduced this to the one that fixes this as pre-releases, and bump a new release with the fix into cf-release/develop.

/cc @zankich @christianang

**Comment by Gerg** [comment]
We saw this today on CAPI.

**Comment by zankich** [comment]
A fix has been pushed to cf-release https://github.com/cloudfoundry/cf-release/commit/71c595db62413cc21f6bbc340f9acfd445fa09ea
