### ISSUE TITLE
Add availability zone tag to registered services

### ISSUE THREAD

**Issue by jtarchie** [cloudfoundry-incubator/consul-release#54]
As a user of consul-release,
When I register a service,
Then I can access that service at its URL with the availability zone as a prefix.

For example, `doppler.service.cf.internal` in the `z1` availability zone would also be available at `z1.doppler.service.cf.internal` as well.

**Comment by keymon** [comment]
+1 you can see this problem in https://github.com/cloudfoundry/cf-release/commit/8980f198

**Comment by jtarchie** [comment]
@keymon, this was added [here](https://github.com/cloudfoundry-incubator/consul-release/commit/bcdd35d6cc24740de3342faedffe1e41d98d7526). The issue just wasn't closed.
