### ISSUE TITLE
Allow to use consul with dnsmasq

### ISSUE THREAD

**Issue by CAFxX** [cloudfoundry-incubator/consul-release#55]
Consul is [hardcoded to listen on port 53](https://github.com/cloudfoundry-incubator/consul-release/blob/b58ff36bfe70995fc1b6d30e5dbb05e94dcb69db/src/confab/config/consul_config_definer.go#L75-L77). This is great unless you want to have something else (e.g. dnsmasq) listening on port 53. 

It is worth noting that even the [consul documentation for DNS forwarding](https://www.consul.io/docs/guides/forwarding.html) suggests to use consul behind dnsmasq/bind. In such a setup dnsmasq is listening on port 53 and consul is on a different port (8600 by default). Only queries for the consul domain are forwarded to consul by dnsmasq; every other query can be handled independently by dnsmasq - with all the flexibility this buys you.

While the current behavior (consul on 53) may be fine for most users, we would like to propose to have the DNS port consul is listening on configurable - so that users that need flexibility in their choice of local DNS server can be accommodated.

A second option would be to include as an option dnsmasq right in this release. I suspect this would be a harder sell though - although it would provide a package that works out of the box.

**Comment by christianang** [comment]
Hi @CAFxX,

Sorry for the delay on responding. Sounds reasonable to allow configuring consul's dns port. We have made a commit to allow this [5a9d336](https://github.com/cloudfoundry-incubator/consul-release/commit/5a9d336315788f3260a8bf6217a7f918dab1957a). With this change you should be able to set `consul.agent.ports.dns` in your bosh manifest to configure consul's dns port. Currently, working its way through our pipeline so we should be cutting a release with this change soon.

However, I don't think we will go as far as to include dnsmasq in the release, but this should allow you to colocate a dnsmasq job with consul yourself.

I'll be closing this issue now, but feel free to reopen if necessary.

Thanks,
Christian

**Comment by CAFxX** [comment]
Amazing, thanks!
