### ISSUE TITLE
Rotating keys/certificates without downtime?

### ISSUE THREAD

**Issue by cnelson** [cloudfoundry-incubator/consul-release#58]
I attempted to rotate the certificates in our consul cluster and it did not restart without intervention (reseting the entire cluster as described here: https://github.com/cloudfoundry-incubator/consul-release#failed-deploys-upgrades-split-brain-scenarios-etc) but during that process, there's obviously a bit of time when all nodes are down.

Did I miss something?  Is it possible to rotate certificates without downtime?  If not, any thoughts on how to best accomplish this?  I'd be happy to provide a PR to make this possible

**Comment by christianang** [comment]
Hi @cnelson,

Sorry for the late response. There is a specific way to rotate consul credentials with zero downtime documented here - https://docs.cloudfoundry.org/deploying/common/consul-security.html#rotating-certs, which admittedly is not easy to find from our README, but we will reference it in our README for future reference.

Let us know if you have any issues.

Thanks,
Christian
