### ISSUE TITLE
Metron agent won't start: Could not use GRPC creds for client: failed to load keypair: tls: failed to find any PEM data in certificate input

### ISSUE THREAD

**Issue by cwb124** [cloudfoundry-incubator/consul-release#71]
Pretty stuck on this one and I'm 99% sure it's cert related but I can't figure out how to fix.   I am doing a brand new bosh deploy to vsphere and I followed the cloud foundry steps exactly (found some doc issues and submitted PRs but you get the idea).

I used the following stub manifest:  https://docs.cloudfoundry.org/deploying/common/vsphere-vcloud-cf-stub.html as a starting point before doing the spiff yaml join to create a manifest.yml

The only place metron is mentioned there in that stub file is under loggregator and the loggregator certs.  However in the final deployment manifest it shows up twice, once as the metron_agent and one under tls so that's slightly confusing.  I used the script in the cf-release repo as per the docs to generate loggregator certs and it didn't seem work.   

I also tried the generate certs script in this consul-release repo and used those certs and still no.  

Here's my bosh instances --ps output:
consul_z1/0 (ffd7742b-c829-430f-918e-021e8d0b211f)*                        | failing | n/a | small_z1  | 172.28.158.117 |
|   consul_agent                                                             | running |     |           |                |
|   metron_agent                                                             | failing |     |           |                |

The metron.log file simply has a pile of these entries:
2017/08/03 01:51:23 Could not use GRPC creds for client: unable to load ca cert file

I've been going in circles so perhaps someone can explain to me what the end deployment manifest needs to look like in terms of the certs for metron_agent.  

There are two instances of cert/key pair in my deployment manifest for metron and they are identical.  Like I said, one is nested under tls and one is simply under metron_agent.  

Where/how is the best way to generate those certs and should I put those certs in my stub previous to spiffing rather than use the generate loggregator cert script in cf-release?  Or, should I just create new certs and dump them into both places (or one place) in my deployment manifest and deploy from there?  I appreciate any help or direction here.

**Comment by asmonter** [comment]
Hi cwb124 ,
I have the same issue.
Could you correct the error?

**Comment by cwb124** [comment]
I didn't correct this error specifically. I rebuilt my deployment manifest paying very close attention to the Cloud Foundry install instructions and cert creation steps and I got past this error.  I have no idea what I fixed.

**Comment by asmonter** [comment]
ok thanks, i will try the same.

**Comment by cwb124** [comment]
Sorry I couldn't be of more help.  One thing I will stress is pay VERY close attention to how they want you to create certs.  Also as a reference, check the openstack or AWS docs for the same steps you're doing in vsphere (or vice versa) because I've found the documentation to be a little inconsistent.  Sometimes the openstack docs had more up to date info that worked vs. the docs for the vsphere part.
