### ISSUE TITLE
BOSH2 Consul not running after update

### ISSUE THREAD

**Issue by gnbfe** [cloudfoundry-incubator/consul-release#74]
Hi all,
I am trying to setup Cloud Foundry with BOSH2 on linux-fedora and in the step of deploying cloud foundry with the command :+1: 
$ bosh2 -e vbox -d cf deploy cf-deployment.yml -o operations/bosh-lite.yml --vars-store deployment-vars.yml -v system_domain=bosh-lite.com

one task failed with the following error :+1: 
"time":1503364084,"error":{"code":400007,"message":"''consul/0 (cee44860-1ef4-4792-b759-233e57bb7865)'' is not running after update. Review logs for failed jobs: consul_agent, metron_agent"}}

what are the root causes of such failure ?
which logs shall i look to ?

Thanks and Regards,
gnbfe

**Comment by genevievelesperance** [comment]
The logs for the consul_agent can be found at `/var/vcap/sys/logs/consul/consul_agent...`.

You may want to bring your logs to the cloud foundry (#bosh)[https://cloudfoundry.slack.com/messages/C02HPPYQ2/details/] channel.
