### ISSUE TITLE
Cloud Foundry setup failure faced

### ISSUE THREAD

**Issue by gnbfe** [cloudfoundry-incubator/consul-release#80]
we are trying to setup cloud foundry on a linux bare metal machine.

this used to work for us , but recently we are facing an issue with cloud foundry setup.

[root@savagnin07 cf-deployment]# bosh2 -e vbox -d cf deploy cf-deployment.yml -o operations/bosh-lite.yml --vars-store deployment-vars.yml -v system_domain=bosh-lite.com
...
+       loggregator:
+         ca_cert: "<redacted>"
+         cert: "<redacted>"
+         key: "<redacted>"
+         use_v2_api: "<redacted>"
+       tcp:
+         enabled: "<redacted>"
+       uaa:
+         ca_cert: "<redacted>"
+         client_secret: "<redacted>"
+     release: diego
+   - name: garden-cni
+     release: cf-networking
+   - name: netmon
+     release: cf-networking
+   - name: vxlan-policy-agent
+     properties:
+       cf_networking:
+         vxlan_policy_agent:
+           ca_cert: "<redacted>"
+           client_cert: "<redacted>"
+           client_key: "<redacted>"
+     release: cf-networking
+   - name: silk-daemon
+     properties:
+       cf_networking:
+         silk_daemon:
+           ca_cert: "<redacted>"
+           client_cert: "<redacted>"
+           client_key: "<redacted>"
+     release: cf-networking
+   - name: cni
+     release: cf-networking
+   name: diego-cell
+   networks:
+   - name: default
+   stemcell: default
+   vm_extensions:
+   - 100GB_ephemeral_disk
+   vm_type: small-highmem
+ - azs:
+   - z1
+   - z2
+   instances: 1
+   jobs:
+   - consumes:
+       consul_client:
+         from: consul_client_link
+       consul_common:
+         from: consul_common_link
+       consul_server: nil
+     name: consul_agent
+     properties:
+       consul:
+         agent:
+           services:
+             loggregator_trafficcontroller: {}
+             reverse_log_proxy: {}
+     release: consul
+   - consumes:
+       doppler:
+         from: doppler
+     name: loggregator_trafficcontroller
+     properties:
+       cc:
+         internal_service_hostname: "<redacted>"
+         mutual_tls:
+           ca_cert: "<redacted>"
+         tls_port: "<redacted>"
+       loggregator:
+         tls:
+           ca_cert: "<redacted>"
+           cc_trafficcontroller:
+             cert: "<redacted>"
+             key: "<redacted>"
+           trafficcontroller:
+             cert: "<redacted>"
+             key: "<redacted>"
+         uaa:
+           client_secret: "<redacted>"
+       ssl:
+         skip_cert_verify: "<redacted>"
+       system_domain: "<redacted>"
+       uaa:
+         ca_cert: "<redacted>"
+         internal_url: "<redacted>"
+     release: loggregator
+   - name: reverse_log_proxy
+     properties:
+       loggregator:
+         tls:
+           ca_cert: "<redacted>"
+           reverse_log_proxy:
+             cert: "<redacted>"
+             key: "<redacted>"
+     provides:
+       reverse_log_proxy:
+         as: reverse_log_proxy
+     release: loggregator
+   - name: route_registrar
+     properties:
+       route_registrar:
+         routes:
+         - name: "<redacted>"
+           port: "<redacted>"
+           registration_interval: "<redacted>"
+           uris:
+           - "<redacted>"
+         - name: "<redacted>"
+           port: "<redacted>"
+           registration_interval: "<redacted>"
+           uris:
+           - "<redacted>"
+           - "<redacted>"
+     release: routing
+   - name: metron_agent
+     properties:
+       loggregator:
+         tls:
+           ca_cert: "<redacted>"
+           metron:
+             cert: "<redacted>"
+             key: "<redacted>"
+       metron_endpoint:
+         shared_secret: "<redacted>"
+     release: loggregator
+   name: log-api
+   networks:
+   - name: default
+   stemcell: default
+   update:
+     max_in_flight: 1
+     serial: true
+   vm_type: minimal
  
+ name: cf
  
+ variables: []

Continue? [yN]: y

Task 60

Task 60 | 12:36:35 | Preparing deployment: Preparing deployment (00:00:02)
Task 60 | 12:36:41 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 60 | 12:36:42 | Compiling packages: cloud_controller_ng/caaa220cf364b68b0c2e20fa31766c570aff583a49ed5b12ebe4d877bb508c08 (00:08:11)
                   L Error: Action Failed get_task: Task 83a8049b-2ab0-4f1a-7688-84ed29166fa6 result: Compiling package cloud_controller_ng: Running packaging script: Running packaging script: Command exited with 5; Stdout: installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Installing rake 12.1.0
Installing i18n 0.8.6
Installing minitest 5.10.3
Installing thread_safe 0.3.6
Installing builder 3.2.3
Installing erubis 2.7.0
Installing mini_portile2 2.1.0
Installing rack 1.6.8
Installing addressable 2.4.0
Installing ast 2.3.0
Installing extlib 0.9.16
Installing multi_json 1.12.2
Installing awesome_print 1.7.0
Installing multipart-post 2.0.0
Installing concurrent-ruby 1.0.5
Installing unf_ext 0.0.7.2 with native extensions
Installing timeliness 0.3.8
Installing backports 3.6.8
Installing beefcake 1.0.0
Installing bit-struct 0.15.0
Installing msgpack 1.1.0 with native extensions
Installing yajl-ruby 1.3.0 with native extensions
Installing byebug 9.0.6 with native extensions
Installing google-protobuf 3.4.1.1 (x86_64-linux)
Installing jwt 1.5.6
Installing little-plugger 1.1.4
Installing memoist 0.16.0
Installing os 0.9.6
Installing httpclient 2.8.2.4
Installing cloudfront-signer 3.0.0
Installing docile 1.1.5
Installing json 1.8.6 with native extensions
Installing simplecov-html 0.10.0
Installing coderay 1.1.1
Installing cookiejar 0.3.0
Installing safe_yaml 1.0.4
Installing daemons 1.2.4
Installing debase-ruby_core_source 0.9.10
Installing diff-lcs 1.3
Installing eventmachine 1.0.9.1 with native extensions
Installing http_parser.rb 0.6.0 with native extensions
Installing excon 0.54.0
Installing fakefs 0.10.0
Installing formatador 0.2.5
Installing ipaddress 0.8.3
Installing mime-types 2.6.2
Installing netrc 0.11.0
Installing retriable 1.4.1
Installing hashdiff 0.3.4
Installing json_pure 1.8.6
Installing machinist 1.0.6
Installing membrane 1.1.0
Installing method_source 0.8.2
Installing middleware 0.1.0
Installing mustache 0.99.8
Installing mysql2 0.4.8 with native extensions
Installing net-ssh 2.9.2
Installing netaddr 1.5.1
Installing newrelic_rpm 3.18.1.330
Installing parallel 1.10.0
Installing pg 0.19.0 with native extensions
Installing posix-spawn 0.3.13 with native extensions
Installing powerpack 0.1.1
Installing thor 0.20.0
Installing slop 3.6.0
Installing public_suffix 1.5.3
Installing rfc822 0.1.5
Installing sexp_processor 4.7.0
Installing rspec-support 3.4.1
Installing ruby-progressbar 1.8.1
Installing unicode-display_width 1.2.1
Installing rubyzip 1.2.1
Installing sequel 4.49.0
Installing tilt 2.0.8
Installing statsd-ruby 1.4.0
Installing timecop 0.8.1
Installing uuidtools 2.1.5
Using vcap-concurrency 0.1.0 from https://github.com/cloudfoundry/vcap-concurrency.git (at /var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/cache/vcap-concurrency-2a5b0179642c)
Installing vmstat 2.1.0 with native extensions
Using bundler 1.14.6
Installing rainbow 2.2.2 with native extensions
Installing ruby-debug-ide 0.6.1.beta4 with native extensions
Installing tzinfo 1.2.3
Installing nokogiri 1.7.2 with native extensions
Installing rack-test 0.6.3
Installing rack-protection 1.5.3
Installing launchy 2.4.3
Installing json-schema 2.8.0
Installing parser 2.4.0.0
Installing autoparse 0.3.3
Installing faraday 0.13.1
Installing unf 0.1.4
Installing loggregator_emitter 5.2.0
Installing vhd 0.0.4
Installing fluent-logger 0.7.1
Installing logging 2.2.2
Installing cf-uaa-lib 3.11.0
Installing simplecov 0.12.0
Installing crack 0.4.3
Installing debase 0.2.2.beta10 with native extensions
Installing em-socksify 0.3.1
Installing thin 1.7.0 with native extensions
Installing fog-core 1.43.0
Installing parallel_tests 2.13.0
Installing pry 0.10.4
Installing ruby_parser 3.8.3
Installing rspec-core 3.4.4
Installing rspec-expectations 3.4.0
Installing rspec-mocks 3.4.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/ruby-debug-ide-0.6.1.beta4/ext
/var/vcap/packages/ruby-2.4/bin/ruby mkrf_conf.rb
Installing base gem
Unable to resolve dependency: user requested 'debase (> 0)'
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/resolver/installer_set.rb:71:in
`add_always_install'
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:474:in
`resolve_dependencies'
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:384:in
`install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in
/var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/ruby-debug-ide-0.6.1.beta4
for inspection.
Results logged to
/var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/ruby-debug-ide-0.6.1.beta4/gem_make.out

An error occurred while installing ruby-debug-ide (0.6.1.beta4), and Bundler
cannot continue.
Make sure that `gem install ruby-debug-ide -v '0.6.1.beta4'` succeeds before
bundling.
, Stderr: + cp -a capi-release/src/cloud_controller_ng /var/vcap/packages/cloud_controller_ng
+ cd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
+ mariadb_dir=/var/vcap/packages/mariadb_connector_c
+ libpq_dir=/var/vcap/packages/libpq
+ bundle_cmd=/var/vcap/packages/ruby-2.4/bin/bundle
+ /var/vcap/packages/ruby-2.4/bin/bundle config build.pg --with-pg-lib=/var/vcap/packages/libpq/lib --with-pg-include=/var/vcap/packages/libpq/include
+ /var/vcap/packages/ruby-2.4/bin/bundle config build.mysql2 --with-mysql-config=/var/vcap/packages/mariadb_connector_c/bin/mariadb_config
+ /var/vcap/packages/ruby-2.4/bin/bundle install --local --deployment --without development test

Task 60 | 12:44:53 | Error: Action Failed get_task: Task 83a8049b-2ab0-4f1a-7688-84ed29166fa6 result: Compiling package cloud_controller_ng: Running packaging script: Running packaging script: Command exited with 5; Stdout: installing your bundle as root will break this application for all non-root
users on this machine.
Warning: the running version of Bundler (1.14.6) is older than the version that created the lockfile (1.15.4). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
Installing rake 12.1.0
Installing i18n 0.8.6
Installing minitest 5.10.3
Installing thread_safe 0.3.6
Installing builder 3.2.3
Installing erubis 2.7.0
Installing mini_portile2 2.1.0
Installing rack 1.6.8
Installing addressable 2.4.0
Installing ast 2.3.0
Installing extlib 0.9.16
Installing multi_json 1.12.2
Installing awesome_print 1.7.0
Installing multipart-post 2.0.0
Installing concurrent-ruby 1.0.5
Installing unf_ext 0.0.7.2 with native extensions
Installing timeliness 0.3.8
Installing backports 3.6.8
Installing beefcake 1.0.0
Installing bit-struct 0.15.0
Installing msgpack 1.1.0 with native extensions
Installing yajl-ruby 1.3.0 with native extensions
Installing byebug 9.0.6 with native extensions
Installing google-protobuf 3.4.1.1 (x86_64-linux)
Installing jwt 1.5.6
Installing little-plugger 1.1.4
Installing memoist 0.16.0
Installing os 0.9.6
Installing httpclient 2.8.2.4
Installing cloudfront-signer 3.0.0
Installing docile 1.1.5
Installing json 1.8.6 with native extensions
Installing simplecov-html 0.10.0
Installing coderay 1.1.1
Installing cookiejar 0.3.0
Installing safe_yaml 1.0.4
Installing daemons 1.2.4
Installing debase-ruby_core_source 0.9.10
Installing diff-lcs 1.3
Installing eventmachine 1.0.9.1 with native extensions
Installing http_parser.rb 0.6.0 with native extensions
Installing excon 0.54.0
Installing fakefs 0.10.0
Installing formatador 0.2.5
Installing ipaddress 0.8.3
Installing mime-types 2.6.2
Installing netrc 0.11.0
Installing retriable 1.4.1
Installing hashdiff 0.3.4
Installing json_pure 1.8.6
Installing machinist 1.0.6
Installing membrane 1.1.0
Installing method_source 0.8.2
Installing middleware 0.1.0
Installing mustache 0.99.8
Installing mysql2 0.4.8 with native extensions
Installing net-ssh 2.9.2
Installing netaddr 1.5.1
Installing newrelic_rpm 3.18.1.330
Installing parallel 1.10.0
Installing pg 0.19.0 with native extensions
Installing posix-spawn 0.3.13 with native extensions
Installing powerpack 0.1.1
Installing thor 0.20.0
Installing slop 3.6.0
Installing public_suffix 1.5.3
Installing rfc822 0.1.5
Installing sexp_processor 4.7.0
Installing rspec-support 3.4.1
Installing ruby-progressbar 1.8.1
Installing unicode-display_width 1.2.1
Installing rubyzip 1.2.1
Installing sequel 4.49.0
Installing tilt 2.0.8
Installing statsd-ruby 1.4.0
Installing timecop 0.8.1
Installing uuidtools 2.1.5
Using vcap-concurrency 0.1.0 from https://github.com/cloudfoundry/vcap-concurrency.git (at /var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/cache/vcap-concurrency-2a5b0179642c)
Installing vmstat 2.1.0 with native extensions
Using bundler 1.14.6
Installing rainbow 2.2.2 with native extensions
Installing ruby-debug-ide 0.6.1.beta4 with native extensions
Installing tzinfo 1.2.3
Installing nokogiri 1.7.2 with native extensions
Installing rack-test 0.6.3
Installing rack-protection 1.5.3
Installing launchy 2.4.3
Installing json-schema 2.8.0
Installing parser 2.4.0.0
Installing autoparse 0.3.3
Installing faraday 0.13.1
Installing unf 0.1.4
Installing loggregator_emitter 5.2.0
Installing vhd 0.0.4
Installing fluent-logger 0.7.1
Installing logging 2.2.2
Installing cf-uaa-lib 3.11.0
Installing simplecov 0.12.0
Installing crack 0.4.3
Installing debase 0.2.2.beta10 with native extensions
Installing em-socksify 0.3.1
Installing thin 1.7.0 with native extensions
Installing fog-core 1.43.0
Installing parallel_tests 2.13.0
Installing pry 0.10.4
Installing ruby_parser 3.8.3
Installing rspec-core 3.4.4
Installing rspec-expectations 3.4.0
Installing rspec-mocks 3.4.1
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/ruby-debug-ide-0.6.1.beta4/ext
/var/vcap/packages/ruby-2.4/bin/ruby mkrf_conf.rb
Installing base gem
Unable to resolve dependency: user requested 'debase (> 0)'
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/resolver/installer_set.rb:71:in
`add_always_install'
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:474:in
`resolve_dependencies'
/var/vcap/packages/ruby-2.4/lib/ruby/site_ruby/2.4.0/rubygems/dependency_installer.rb:384:in
`install'
  mkrf_conf.rb:35:in `rescue in <main>'
  mkrf_conf.rb:28:in `<main>'

rake failed, exit code 1

Gem files will remain installed in
/var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/bundle/ruby/2.4.0/gems/ruby-debug-ide-0.6.1.beta4
for inspection.
Results logged to
/var/vcap/data/packages/cloud_controller_ng/0fc95ac72d429f5d1c7e3f4880a9e5e9ff018d14/cloud_controller_ng/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0-static/ruby-debug-ide-0.6.1.beta4/gem_make.out

An error occurred while installing ruby-debug-ide (0.6.1.beta4), and Bundler
cannot continue.
Make sure that `gem install ruby-debug-ide -v '0.6.1.beta4'` succeeds before
bundling.
, Stderr: + cp -a capi-release/src/cloud_controller_ng /var/vcap/packages/cloud_controller_ng
+ cd /var/vcap/packages/cloud_controller_ng/cloud_controller_ng
+ mariadb_dir=/var/vcap/packages/mariadb_connector_c
+ libpq_dir=/var/vcap/packages/libpq
+ bundle_cmd=/var/vcap/packages/ruby-2.4/bin/bundle
+ /var/vcap/packages/ruby-2.4/bin/bundle config build.pg --with-pg-lib=/var/vcap/packages/libpq/lib --with-pg-include=/var/vcap/packages/libpq/include
+ /var/vcap/packages/ruby-2.4/bin/bundle config build.mysql2 --with-mysql-config=/var/vcap/packages/mariadb_connector_c/bin/mariadb_config
+ /var/vcap/packages/ruby-2.4/bin/bundle install --local --deployment --without development test

Task 60 Started  Mon Oct 23 12:36:35 UTC 2017
Task 60 Finished Mon Oct 23 12:44:53 UTC 2017
Task 60 Duration 00:08:18
Task 60 error

Updating deployment:
  Expected task '60' to succeed but state is 'error'

Exit code 1

this error occurs even if gems list lists the following packages as installed
[root@savagnin07 cf-deployment]# gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.3.0)
bundler (1.15.4)
bundler-unload (1.0.2)
debase (0.2.1)
debase-ruby_core_source (0.9.11)
did_you_mean (1.1.0)
executable-hooks (1.3.2)
gem-wrappers (1.3.2)
io-console (default: 0.4.6)
json (2.1.0, default: 2.0.2)
minitest (5.10.1)
net-telnet (0.1.1)
openssl (default: 2.0.2)
power_assert (0.4.1)
psych (default: 2.2.2)
rake (12.0.0)
rdoc (default: 5.0.0)
ruby-debug-ide (0.6.1.beta4)
rubygems-bundler (1.4.4)
rvm (1.11.3.9)
test-unit (3.2.3)
xmlrpc (0.2.1)
[root@savagnin07 cf-deployment]#

**Comment by genevievelesperance** [comment]
Hi @gnbfe. Did you use `bbl` to create this environment? This error seems bosh2 related and you may want to ask in the #bosh channel in cloudfoundry.slack.com or on the github.com/cloudfoundry/bosh-cli repo.

**Comment by gnbfe** [comment]
Hi genevievelesperance,
no i have not used bb1, what is bb1 ?

i will ask on #bosh channel to see if i can get some help on this issue which is blocking me from installing Cloud Foundry

Regards

**Comment by evanfarrar** [comment]
Hi @gnbfe I can't tell how this is related to consul-release, if anything there is a BOSH or Cloud Controller build pre-requisite that is missing. You may have better luck asking in slack for direction. Closing for now, please re-open if you are still having issues.
