### ISSUE TITLE
clone failed

### ISSUE THREAD

**Issue by christinayhh** [cloudfoundry-incubator/consul-release#82]
vagrant@bosh-lite:~/workspace/cf-release/src/consul-release$ git config --global https.proxy https://127.0.0.1:1080
vagrant@bosh-lite:~/workspace/cf-release/src/consul-release$ git submodule update --init
Cloning into 'src/acceptance-tests/vendor/golang.org/x/crypto'...
fatal: unable to access 'https://go.googlesource.com/crypto/': Failed to connect to go.googlesource.com port 443: Connection timed out
Clone of 'https://go.googlesource.com/crypto' into submodule path 'src/acceptance-tests/vendor/golang.org/x/crypto' failed

What is the solution?

**Comment by genevievelesperance** [comment]
This seems like a firewall issue and not an issue with the consul-release repo itself. Can you check that you have access to that url at all?
