### ISSUE TITLE
Consul results are not cached on windows

### ISSUE THREAD

**Issue by jvshahid** [cloudfoundry-incubator/consul-release#83]
## Context

Historically we have disabled the windows [Dnscache service](https://technet.microsoft.com/en-us/library/cc940045.aspx) because it was caching negative results (i.e. failure to resolve a name) which caused long outages if windows tried to query consul agent while it was down (e.g. while consul agent is restarting). We later realized that the consul agent isn't very stable and would sometimes fail to resolve names (which is something the Diego team is experiencing). @mhoran mentioned that the current solution is to enable the Dnscache service. Set `MaxNegativeCacheTtl` to `0` in order to prevent caching of failures and rely on Dnscache service to cache entries so that we don't have to rely on the consul agent being very reliable

I am not sure if the caching of `.service.cf.internal` entries has been verified or if that's a recent regression. I am inclined to say it is the former since [consul docs](https://www.consul.io/docs/guides/dns-cache.html) indicates that the default TTL is set to 0 to prevent caching. You can also check the ttl of the record returned from consul by running

```
nslookup.exe -q=mx bbs.service.cf.internal
```

## Expected bevavior

when i run

```
ping bbs.service.cf.internal
```

I expect the output of `ipconfig /displaydns` to include a record for `bbs.service.cf.internal` to indicate that the entry is cached

## Actual behavior

I do not see any `.cf.internal` entries in the dns cache

**Comment by evanfarrar** [comment]
https://github.com/cloudfoundry-incubator/consul-release/releases/tag/v191 contains a property for this, I want to close, but I also want your feedback on what you find to be a sane default value for that property (i.e. what makes WATS pass reliably).

**Comment by genevievelesperance** [comment]
Related thread: https://cloudfoundry.slack.com/archives/C02FM2BPE/p1513711925000203?thread_ts=1513227292.000131&cid=C02FM2BPE

**Comment by genevievelesperance** [comment]
Made a PR for the windows-cell ops-file ^ and the value can be changed based on WATS needs.
